services:
  app:
    image: knekvasil/gin13:latest
    container_name: gin13
    ports:
      - "2567:2567"
    env_file: .env
    restart: unless-stopped
    networks:
      - db-net

networks:
  db-net:
    external: true
